VERIFICADOR = [] 
MULTIPLICADOR = 10
#CPF = list('393925668')
CPF_ORIGINAL = list(input('INFORME SEU CPF COMPLETO: ').replace(".","").replace("-",""))
CPF = CPF_ORIGINAL[:-2]
DV = CPF_ORIGINAL[9:]
#print(DV)

#PRIMEIRO DIGÍTO
for d in CPF:
    VERIFICADOR.append(int(d)*(MULTIPLICADOR))  
    MULTIPLICADOR = MULTIPLICADOR -1
  
PRIMEIRO_DIGITO= (sum(VERIFICADOR)*10)%11

#SEGUNDO DIGÍTO
CPF.append(PRIMEIRO_DIGITO)
MULTIPLICADOR = 11
VERIFICADOR = []

for d in CPF:
    VERIFICADOR.append(int(d)*(MULTIPLICADOR))
    MULTIPLICADOR = MULTIPLICADOR -1
SEGUNDO_DIGITO= (sum(VERIFICADOR)*10)%11

print(f'DIGÍTO VERIFICADOR ENCONTRADO: {PRIMEIRO_DIGITO}{SEGUNDO_DIGITO}')
print(int(''.join(DV)) == (PRIMEIRO_DIGITO*10 + SEGUNDO_DIGITO))


